modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
issueTrackerURL="https://github.com/lazynessmind/HorseModifiers/issues" #optional
[[mods]] #mandatory
modId="horsemodifiers" #mandatory
version="1.0.1" #mandatory
displayName="Horse Modifiers" #mandatory
updateJSONURL="https://raw.githubusercontent.com/lazynessmind/HorseModifiers/dev/update.json" #optional
displayURL="http://lazynessmind.com/" #optional TODO
logoFile="examplemod.png" #optional TODO
credits="McJty (Tutorials 1.14)" #optional
authors="lazynessmind" #optional
description='''
Horses can be bred among themselves to create a better horse, so this mod changes this by adding carrots that alter the horse's attributes.
'''