modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory
license="MIT" #mandatory
issueTrackerURL="https://github.com/lazynessmind/HorseModifiers/issues" #optional
[[mods]] #mandatory
modId="horsemodifiers" #mandatory
version="1.3" #mandatory
displayName="Horse Modifiers" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/horse-modifiers" #optional TODO
logoFile="" #optional TODO
credits="" #optional
authors="lazynessmind" #optional
description='''
Horses can be bred among themselves to create a better horse, so this mod changes this by adding carrots that alter the horse's attributes.
'''